id = "roules-min-theme"
name = "Roules Min Theme"
version = "0.2.1"
schema_version = 1
authors = ["roules"]
description = "A port of miguelsolorio's Min Theme for Zed. by Phillip Bronzel, adapted by roules"
repository = "https://github.com/roules-dev/roules-min-theme"
